version: '3.7'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    working_dir: /var/www
    ports:
      - 9000:80
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:5.7
    restart: always
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
  adminer:
    image: adminer
    restart: always
    ports:
      - 4000:8080
    depends_on:
      - db
    links:
      - db