version: '3.1'
services:
  node:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - /var/www/backoffice-administration:/home/node/app
    command: "node server.js"
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 884191
      MYSQL_DATABASE: teste

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
